"""model check

Revision ID: 0ec5c90bc06e
Revises: eebcb369aace
Create Date: 2025-04-24 08:38:42.774578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ec5c90bc06e'
down_revision: Union[str, None] = 'eebcb369aace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'password_reset_token', ['id'])
    op.create_unique_constraint(None, 'two_factor_confirmation', ['id'])
    op.create_unique_constraint(None, 'two_factor_token', ['id'])
    op.create_unique_constraint(None, 'verification_token', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_token', type_='unique')
    op.drop_constraint(None, 'two_factor_token', type_='unique')
    op.drop_constraint(None, 'two_factor_confirmation', type_='unique')
    op.drop_constraint(None, 'password_reset_token', type_='unique')
    op.alter_column('activities', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
