"""model check

Revision ID: 6f65b2685b88
Revises: 0ec5c90bc06e
Create Date: 2025-04-24 11:04:51.592983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f65b2685b88'
down_revision: Union[str, None] = '0ec5c90bc06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('learning_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_teachers_class_id', sa.UUID(), nullable=True),
    sa.Column('teachers_class_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['subject_teachers_class_id'], ['subject_teachers_classes.id'], ),
    sa.ForeignKeyConstraint(['teachers_class_id'], ['teachers_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dob', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('learning_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('subject_teachers_class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('teachers_class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_teachers_class_id'], ['subject_teachers_classes.id'], name='students_subject_teachers_class_id_fkey'),
    sa.ForeignKeyConstraint(['teachers_class_id'], ['teachers_classes.id'], name='students_teachers_class_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='students_pkey'),
    sa.UniqueConstraint('id', name='students_id_key')
    )
    op.drop_table('teachers_students')
    # ### end Alembic commands ###
