"""Initial migration

Revision ID: a68f4d474261
Revises: 19bc0fd59df0
Create Date: 2025-03-31 13:58:26.156021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68f4d474261'
down_revision: Union[str, None] = '19bc0fd59df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'activities', ['id'])
    op.drop_constraint('activities_user_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activities', 'user')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('activities', sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_user_fkey', 'activities', 'users', ['user'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'activities', type_='unique')
    op.drop_column('activities', 'user_id')
    # ### end Alembic commands ###
