"""model check

Revision ID: dcb39447e2fd
Revises: 6f65b2685b88
Create Date: 2025-04-24 14:46:10.636500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb39447e2fd'
down_revision: Union[str, None] = '6f65b2685b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers_students', sa.Column('parent_phone_number', sa.String(), nullable=True))
    op.add_column('teachers_students', sa.Column('parent_email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'teachers_students', ['id'])
    op.drop_column('teachers_students', 'email')
    op.drop_column('teachers_students', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers_students', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teachers_students', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teachers_students', type_='unique')
    op.drop_column('teachers_students', 'parent_email')
    op.drop_column('teachers_students', 'parent_phone_number')
    # ### end Alembic commands ###
