"""model check

Revision ID: e6862b39df1e
Revises: b69b25d66d23
Create Date: 2025-04-27 12:54:27.461158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6862b39df1e'
down_revision: Union[str, None] = 'b69b25d66d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teachers_class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['teachers_students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teachers_class_id'], ['teachers_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_attendance')
    # ### end Alembic commands ###
