"""model check

Revision ID: eebcb369aace
Revises: bc8a30f66b53
Create Date: 2025-04-24 07:46:16.296874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebcb369aace'
down_revision: Union[str, None] = 'bc8a30f66b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'token', name='uq_password_email_token'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('two_factor_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'token', name='uq_2fa_email_token'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('verification_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'token', name='uq_verification_email_token'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('two_factor_confirmation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_2fa_user')
    )
    op.create_unique_constraint(None, 'students', ['id'])
    op.create_unique_constraint(None, 'subject_teachers_classes', ['id'])
    op.create_unique_constraint(None, 'teachers', ['id'])
    op.create_unique_constraint(None, 'teachers_classes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers_classes', type_='unique')
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'subject_teachers_classes', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_table('two_factor_confirmation')
    op.drop_table('verification_token')
    op.drop_table('two_factor_token')
    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
