"""Initial migration

Revision ID: 69b2c7b76f5e
Revises: 971a51298037
Create Date: 2025-03-27 06:58:02.456750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b2c7b76f5e'
down_revision: Union[str, None] = '971a51298037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_args', sa.String(), nullable=True),
    sa.Column('task_kwargs', sa.String(), nullable=True),
    sa.Column('crontab', sa.String(), nullable=False),
    sa.Column('scheduling_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_table('periodic_tasks')
    # ### end Alembic commands ###
